# .github/workflows/deploy-infrastructure.yml
name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: your-org/your-repo/.github/workflows/reusable-workflow.yml@main
    with:
      environment: dev
      terraform_action: apply
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
